version: '3'
services:
  c1-app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: tienda_emi:latest
    container_name: tienda_emi
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - lab4_red
    depends_on:
      - db_tire
    working_dir: /var/www/html

  db_tire:
    image: postgres:15.4
    container_name: db_emi
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tienda_emi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    
    ports:
      - "5432:5432"
    networks:
      - lab4_red

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db_tire
    environment:
      PGADMIN_DEFAULT_EMAIL: maria@gmail.com
      PGADMIN_DEFAULT_PASSWORD: maria
    networks:
    - lab4_red

networks:
  lab4_red: