version: '3'

services:
  
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-lab
    ports:
      - 50000:50000
      - 9091:8080
    restart: always
    volumes:
      - jenkins_data_mod5:/var/jenkins_home
    #  - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - mod5-network

volumes:
  jenkins_data_mod5:
    name: jenkins_data_mod5

networks:
  mod5-network:
      external: true